version: '2'

volumes:
    resin-data:
    dashboard:
    database:

services:
  node-red:
    build: ./node-red
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1' 
    environment:
      - "USERNAME=balena"
      - "PASSWORD=balena"
      - "ENCRIPTION_KEY=balena"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - 80:80

  connector:
    image: bhcr.io/balenablocks/connector-aarch64 # where <arch> is one of aarch64, armv7hf or amd64
    restart: always
    labels:
      io.balena.features.balena-api: '1' # necessary to discover services
      io.balena.features.supervisor-api: 1  # necessary to discover services in local mode
    privileged: true # necessary to change container hostname
  
  influxdb:
    image: influxdb@sha256:b4529fd53e9022bd1e83aaf04c6c6a1ebfffdfa112c31367d69da1354983a24b
    container_name: influxdb
    restart: always
    volumes:
      - 'database:/var/lib/influxdb'
  
  dashboard:
    image: bh.cr/balenablocks/dashboard
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - 'dashboard:/data'

  mqtt:
    image: arm32v6/eclipse-mosquitto
    network_mode: host
    ports:
      - "1883:1883"
    restart: always
